services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - laughing-network
    env_file:
      - .env
    volumes:
      - .:/app
    tty: true

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - laughing-network
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    command: bun run dev
    tty: true

networks:
  laughing-network:
    driver: bridge
