services:
  postgres:
    image: postgres:latest
    ports:
      - "5433:5432"
    networks:
      - laughing-network
    environment:
      POSTGRES_DB: mydata
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "6380:6379"
    networks:
      - laughing-network
    # command: ["redis-server", "--requirepass", "your_redis_password_here"]
    # environment:
    #   REDIS_PASSWORD: your_redis_password_here
    volumes:
      - redis_data:/data

  ai:
    build:
      context: ./ai
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - laughing-network
    volumes:
      - ./ai:/app
    command: uv run uvicorn src.main:app --host 0.0.0.0 --port 8080
    tty: true
    depends_on:
      - postgres
      - redis

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - laughing-network
    env_file:
      - .env
    volumes:
      - .:/app
    tty: true
    depends_on:
      - postgres
      - ai
      - redis

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - laughing-network
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    command: bun run dev
    tty: true

networks:
  laughing-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
